adb push libEGL.so.1.0 /data/ubuntu/usr/lib
adb push libEGL.so.1 /data/ubuntu/usr/lib
adb push libsf.so.1.0 /data/ubuntu/usr/lib
adb push libsf.so.1 /data/ubuntu/usr/lib
adb push libis.so.1.0 /data/ubuntu/usr/lib
adb push libis.so.1 /data/ubuntu/usr/lib
adb push libhardware.so.1.0 /data/ubuntu/usr/lib
adb push libhardware.so.1 /data/ubuntu/usr/lib
adb push libhybris_ics.so /data/ubuntu/usr/lib
adb push libGLESv2.so.2 /data/ubuntu/usr/lib
adb push libGLESv2.so.2.0 /data/ubuntu/usr/lib
adb push test_egl /data/ubuntu/root
adb push test_glesv2 /data/ubuntu/root
adb push test_hw /data/ubuntu/root
adb push test_sensors /data/ubuntu/root
adb push test_sf /data/ubuntu/root
